# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Python image
FROM python:3.12-slim

# Install uv installer and clean cache
RUN pip install --no-cache-dir uv

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock server.py ./

# Install dependencies via uv
RUN uv sync

# Run the MCP server (transport configured via MCP_TRANSPORT env var)
CMD ["uv", "run", "python", "server.py"]
